version: '2'
services:
  gpio_database_generator:
    build: ./gpio_database_generator
    volumes:
      - ./gpio_database_generator/:/gpio_database_generator
    links:
      - db
    # weil Container Zugriff auf Hardware braucht
    privileged: true
    environment:
      - run_mode=prod

  django_web_app:
    build: ./django_web_app
    volumes:
      - ./django_web_app/:/raspi_web_app/django_web_app
    ports:
      - "8000:8000"
    links:
      - db

  db:
    image: "arm32v7/postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=hunter2
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/
