version: '3'
services:
  gpio_database_generator:
    build: ./gpio_database_generator
    volumes:
      - ./gpio_database_generator/:/gpio_database_generator
    links:
      - db
    depends_on:
      - db
    restart: always
    # weil Container Zugriff auf Hardware braucht
    privileged: true
    environment:
      - run_mode=prod
      # für docker log output
      - PYTHONUNBUFFERED=TRUE
    networks:
      - raspi_web_network

  django_web_app:
    build: ./django_web_app
    volumes:
      - ./django_web_app/:/raspi_web_app/django_web_app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    restart: always
    networks:
      - raspi_web_network

  db:
    image: "arm32v7/postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/raspi_web_app_data
    volumes:
      - /mnt/data_storage/raspi_web_app/:/var/lib/postgresql/data/
    #- /var/lib/postgresql/data/:/var/lib/postgresql/data/
    networks:
      - raspi_web_network
    restart: always

networks:
  raspi_web_network:
